on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-22.04
    environment: CI
    env:
      APP_PHONE_NUMBER: ${{ secrets.APP_PHONE_NUMBER }}
      APP_LINKEDIN: ${{ secrets.APP_LINKEDIN }}
      APP_FULLNAME: ${{ secrets.APP_FULLNAME }}
      APP_EMAIL: ${{ secrets.APP_EMAIL }}
      APP_URL: ${{ secrets.APP_URL }}

    services:
      gotenberg:
        image: gotenberg/gotenberg:8.1.0
        ports:
          - "3000:3000"

    steps:
      - name: 🛒 Checkout tag
        uses: actions/checkout@v4

      - name: ✨ Install bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: 1.0.28

      - uses: actions/cache@v4
        name: 📦 Setup deps cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ➕ Install dependencies
        run: |
          bun install --frozen-lockfile
          bun panda codegen

      - name: 📦 Build static output
        run: bun run build

      - name: 📦 Build PDFs
        env:
          APP_RESUME_FR_FILENAME: ${{ secrets.APP_RESUME_FR_FILENAME }}
          APP_RESUME_EN_FILENAME: ${{ secrets.APP_RESUME_EN_FILENAME }}
        run: |
          bun run preview --host 172.17.0.1 &
          sleep 5

          # see https://stackoverflow.com/questions/65497331/github-actions-is-it-possible-to-call-the-runner-host-from-a-docker-container

          curl --request POST "http://localhost:3000/forms/chromium/convert/url" \
            --form url="http://172.17.0.1:4321/fr/pure/index.html" \
            --form paperWidth=8.27 \
            --form paperHeight=11.7 \
            --form marginTop=0.0 \
            --form marginBottom=0.0 \
            --form marginLeft=0.0 \
            --form marginRight=0.0 \
            --form scale=1.322 \
            -o "${APP_RESUME_FR_FILENAME}.pdf"

          curl --request POST "http://localhost:3000/forms/chromium/convert/url" \
            --form url="http://172.17.0.1:4321/en/pure/index.html" \
            --form paperWidth=8.27 \
            --form paperHeight=11.7 \
            --form marginTop=0.0 \
            --form marginBottom=0.0 \
            --form marginLeft=0.0 \
            --form marginRight=0.0 \
            --form scale=1.322 \
            -o "${APP_RESUME_EN_FILENAME}.pdf"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.sha }}"
          tag_name: "untagged-${{ github.sha }}"
          token: ${{ secrets.GH_CREATE_RELEASE_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            *.pdf
